---
# tasks file for arillso.exoscale

- name: get instance data
  cs_instance_info:
    name: "{{ inventory_hostname }}"
  delegate_to: 127.0.0.1
  register: exo_facts

- name: get volume data
  command: "cs listVolumes name={{ exo_facts.instances[0].volumes[0].name }} vmname={{ inventory_hostname }}"
  register: volume
  changed_when: false
  delegate_to: 127.0.0.1
  when: vm_exists.failed

- name: scale volume up
  command: "cs resizeVolume size={{ exoscale_disk }} id={{ volume.stdout | from_json | json_query('volume[0].id') }}"
  delegate_to: 127.0.0.1
  when: vm_exists.failed and exoscale_disk*1000000000 > volume.stdout | from_json | json_query('volume[0].size')
